name: Deploy

on:
 release:
    types:
      - created

jobs:


 ########################################################################################
  checkout:
    name: Checkout
    strategy:
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, clusty, '${{ matrix.machine }}']
    
    steps:
    - name: clean
      run: rm -rf ${{ github.workspace }}/*
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get tags
      run: | 
        cd ./libs/igraph
        git fetch --prune --unshallow
        echo exit code $?
        git tag --list
      continue-on-error: true  
  
########################################################################################
  make:
    name: Make
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux]
        platform: [avx2]
        compiler: [14]
        include:
        - {machine: arm64_linux, platform: arm8, compiler: 12}
        - {machine: x64_mac, platform: avx2, compiler: 12}
        - {machine: arm64_mac, platform: m1, compiler: 12}
        
    runs-on: [self-hosted, clusty, '${{ matrix.machine }}']  
        
    steps:
    - name: make 
      run: make -j32 CXX=g++-${{matrix.compiler}} CC=gcc-${{matrix.compiler}} PLATFORM=${{ matrix.platform }} LEIDEN=true
    - name: tar artifacts
      run: tar -cvzf clusty.tar.gz clusty LICENSE

      
########################################################################################
  help:
    name: Print usage
    needs: make
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, clusty, '${{ matrix.machine }}']
        
    steps:
    - name: help
      run: ./clusty
    - name: version
      run: ./clusty --version

########################################################################################
  upload:
    name: Upload
    needs: help
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, clusty, '${{ matrix.machine }}']
    
    steps:
    - name: deploy
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./clusty.tar.gz
        asset_name: clusty-${{ github.event.release.tag_name }}-${{matrix.machine}}.tar.gz
        asset_content_type: application/gzip
