name: Large data CI

on:
  workflow_dispatch:

jobs:

 ########################################################################################
  checkout:
    name: Checkout
    runs-on: [self-hosted, x64_linux, large]
    
    steps:
    - name: clean
      run: rm -rf ${{ github.workspace }}/*
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get tags
      run: | 
        cd ./libs/igraph
        git fetch --prune --unshallow
        echo exit code $?
        git tag --list
      continue-on-error: true

 ########################################################################################
  make:
    name: Make
    needs: checkout
    strategy:
      matrix:
        compiler: [14]
    runs-on: [self-hosted, x64_linux, large]
    
    steps:
    - name: make
      run: gmake -j32 CXX=g++-${{matrix.compiler}} CC=gcc-${{matrix.compiler}} PLATFORM=avx2 LEIDEN=true STATIC_LINK=true
    - name: print info
      run: ./bin/clusty --help 

 ########################################################################################
  imgvr-variants:
    name: IMGVR clustering variants 
    needs: make
    strategy:
      fail-fast: false
      matrix:
        variant: ['numeric']
        threads: [4,8,16]
        include:
        - {variant: 'numeric',       args: '--numeric-ids --id-cols qidx ridx'}
        - {variant: 'numeric.reps',  args: '--numeric-ids --id-cols qidx ridx --out-representatives', threads: 16}
        - {variant: 'numeric.objs',  args: '--numeric-ids --id-cols qidx ridx --objects-file ${INPUT_DIR}/${DATASET}.ani.ids.tsv', threads: 16}
        - {variant: 'numeric.objs.reps',  args: '--numeric-ids --id-cols qidx ridx --objects-file ${INPUT_DIR}/${DATASET}.ani.ids.tsv --out-representatives', threads: 16}
     
    env:
      INPUT_DIR: ../../../../clusty/input
      TEMP_DIR: ../../../../clusty/temp
      REF_DIR: ../../../../clusty/ref
      DATASET: IMGVR.fraction_02
       
    runs-on: [self-hosted, x64_linux, large] 

    steps:
    - name: cluster
      run: /usr/bin/time -v ./bin/clusty -t ${{ matrix.threads }} ${INPUT_DIR}/${DATASET}.ani.tsv ${TEMP_DIR}/IMGVR.${{ matrix.variant }}.clusty ${{ matrix.args }} --similarity --distance-col ani --min ani 0.95 --min qcov 0.85
    - name: md5
      run: md5sum ${TEMP_DIR}/IMGVR.${{ matrix.variant }}.clusty
#    - name: python compare
#      run: python3 ./test/cmp.py ${TEMP_DIR}/IMGVR.${{ matrix.variant }}.clusty ${REF_DIR}/IMGVR.${{ matrix.variant }}.clusty 
    - name: binary compare
      run: cmp ${TEMP_DIR}/IMGVR.${{ matrix.variant }}.clusty ${REF_DIR}/IMGVR.${{ matrix.variant }}.clusty 

 ########################################################################################
  all-algos:
    name: Clustering algorithms
    needs: imgvr-variants
    strategy:
      fail-fast: false
      matrix:
        dataset: [ICTV, IMGVR]
        algo_name: [single, complete, set-cover, uclust, cd-hit, leiden_07, leiden_10]
        include:
        - {dataset: ICTV, variant_name: full, args: '--numeric-ids --similarity --distance-col tani --min tani 0.95'}
        - {dataset: IMGVR, variant_name: fraction_02, args: '--numeric-ids --similarity --distance-col ani --min ani 0.95 --min qcov 0.85'}
#        - {dataset: IMGVR_HQ, variant_name: full, args: '--numeric-ids --similarity --distance-col ani --min ani 0.95 --min qcov 0.85'}
        - {algo_name: single, algo_cmd: single}
        - {algo_name: complete, algo_cmd: complete}
        - {algo_name: set-cover, algo_cmd: set-cover}
        - {algo_name: uclust, algo_cmd: uclust}
        - {algo_name: cd-hit, algo_cmd: cd-hit}
        - {algo_name: leiden_07, algo_cmd: 'leiden --leiden-resolution 0.7'}
        - {algo_name: leiden_10, algo_cmd: 'leiden --leiden-resolution 1.0'}
     
    env:
      INPUT_DIR: ../../../../clusty/input
      TEMP_DIR: ../../../../clusty/temp
      REF_DIR: ../../../../clusty/ref
       
    runs-on: [self-hosted, x64_linux, large] 

    steps:
    - name: cluster
      run: /usr/bin/time -v ./bin/clusty ${INPUT_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.ani.tsv --objects-file ${INPUT_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.ani.ids.tsv ${TEMP_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty --algo ${{ matrix.algo_cmd }} ${{ matrix.args }}
    - name: md5
      run: md5sum ${TEMP_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty
 #   - name: python compare
 #     run: python3 ./test/cmp.py ${TEMP_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty ${REF_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty 
    - name: binary compare
      run: cmp ${TEMP_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty ${REF_DIR}/${{ matrix.dataset }}.${{ matrix.variant_name }}.${{ matrix.algo_name }}.clusty

